// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/users/:username": {
    params: {
      "username": string;
    };
  };
  "/settings": {
    params: {};
  };
  "/api/tweets": {
    params: {};
  };
  "/api/users/:username": {
    params: {
      "username": string;
    };
  };
  "/api/users/:username/follow": {
    params: {
      "username": string;
    };
  };
  "/api/tweets/:tweetId/like": {
    params: {
      "tweetId": string;
    };
  };
  "/api/auth/login": {
    params: {};
  };
  "/api/auth/register": {
    params: {};
  };
  "/api/auth/verify-email/:token": {
    params: {
      "token": string;
    };
  };
  "/api/upload/avatar": {
    params: {};
  };
  "/api/search": {
    params: {};
  };
  "/search": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/home" | "/users/:username" | "/settings" | "/api/tweets" | "/api/users/:username" | "/api/users/:username/follow" | "/api/tweets/:tweetId/like" | "/api/auth/login" | "/api/auth/register" | "/api/auth/verify-email/:token" | "/api/upload/avatar" | "/api/search" | "/search";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/home";
  };
  "routes/users.$username.tsx": {
    id: "routes/users.$username";
    page: "/users/:username";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/api.tweets.api.tsx": {
    id: "routes/api.tweets.api";
    page: "/api/tweets";
  };
  "routes/api.users.$username.api.tsx": {
    id: "routes/api.users.$username.api";
    page: "/api/users/:username";
  };
  "routes/api.users.$username.follow.api.tsx": {
    id: "routes/api.users.$username.follow.api";
    page: "/api/users/:username/follow";
  };
  "routes/api.tweets.$tweetId.like.api.tsx": {
    id: "routes/api.tweets.$tweetId.like.api";
    page: "/api/tweets/:tweetId/like";
  };
  "routes/api.auth.login.tsx": {
    id: "routes/api.auth.login";
    page: "/api/auth/login";
  };
  "routes/api.auth.register.tsx": {
    id: "routes/api.auth.register";
    page: "/api/auth/register";
  };
  "routes/api.auth.verify-email.$token.api.tsx": {
    id: "routes/api.auth.verify-email.$token.api";
    page: "/api/auth/verify-email/:token";
  };
  "routes/api.upload.avatar.api.tsx": {
    id: "routes/api.upload.avatar.api";
    page: "/api/upload/avatar";
  };
  "routes/api.search.api.tsx": {
    id: "routes/api.search.api";
    page: "/api/search";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
};